### ISSUE TITLE
Create Account doesn't work

### ISSUE THREAD

**Issue by pawelsawicz** [Helbreath/Helbreath.LoginServerConsole#7]
[CreateNewAccount](https://github.com/Helbreath/Helbreath.LoginServerConsole/blob/f7317429a60a0cf4b120972328d8bda21eb6c933/Helbreath.LoginServerConsole/LoginServer.cpp#L3818) is throwing an error that `couldn't create acccount with date 0000-0-00 00:00:00` It's caused probably string concatenation while creating a query to database

**Comment by pawelsawicz** [comment]
Found out that database schema might be broken. Did quick fix but have to look into `account_database` and `CreateDate` column and its Custom Value

**Comment by helbreath2016** [comment]
bro is working in my source take a look at my zip i sent you. acc create
with data base 100% working

**Comment by pawelsawicz** [comment]
fixed by #15
